<?php $this->headtitle('Descartar rendicion'); ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('registry/default', array('action' => 'delete'), array('query' => array('id' => $this->id))));
?>

<div class="page-header">
	<h2><?=$this->translate('Descartar rendicion');?></h2>
</div>

<div class="well well-lg">
	<?=$this->form()->openTag($form);?>
	<div class="text-center">
		<p><?=$this->translate('Esta seguro que desea eliminar la <strong>Rendicion</strong> seleccionada');?></p>
		
		<?=$this->formelement($form->get('element'));?>
		<?=$this->formelement($form->get('csrf'));?>
		
		<a href="<?=$this->url('registry');?>" class="btn btn-labeled btn-default">
			<span class="btn-label"><?=$this->glyphicon('arrow-left');?></span>
			<?=$this->translate('Volver');?></a>
		<button type="submit" class="btn btn-labeled btn-danger">
			<span class="btn-label"><?=$this->glyphicon('remove');?></span>
			<?=$this->translate('Confirmar Eliminacion');?></button>
	</div>
	<?=$this->form()->closeTag();?>
</div>
