<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Registry\Module'                        => __DIR__ . '/Module.php',
    'Registry\Controller\IndexController' => __DIR__ . '/src/Registry/Controller/IndexController.php',
    'RegistryTest\Framework\TestCase'        => __DIR__ . '/tests/Registry/Framework/TestCase.php',
    'RegistryTest\SampleTest'                => __DIR__ . '/tests/Registry/SampleTest.php',
);
